### ISSUE TITLE
Building jackson-jaxrs-json-provider 3.0.0-SNAPSHOT as well as trial to get is from oss fails

### ISSUE THREAD

**Issue by soberich** [FasterXML/jackson-jaxrs-providers#105]
Hi, 
Want to start with jackson-jaxrs-json-provider 3.0.0-SNAPSHOT
but seems not artifacts are in oss repo.

When try to build it from sources I first build and installed locally `annotation`,  `base`,  `core`,  `parent`... etc.
But still got this

```
[ERROR] /C:/Users/Admin/IdeaProjects/__OFFICIAL/jackson-jaxrs-providers/base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/MapperConfiguratorBase.java:[91,17] cannot find symbol
  symbol:   method configure(com.fasterxml.jackson.databind.DeserializationFeature,boolean)
  location: class com.fasterxml.jackson.databind.ObjectMapper
[ERROR] /C:/Users/Admin/IdeaProjects/__OFFICIAL/jackson-jaxrs-providers/base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/MapperConfiguratorBase.java:[95,17] cannot find symbol
  symbol:   method configure(com.fasterxml.jackson.databind.SerializationFeature,boolean)
  location: class com.fasterxml.jackson.databind.ObjectMapper
[ERROR] /C:/Users/Admin/IdeaProjects/__OFFICIAL/jackson-jaxrs-providers/base/src/main/java/com/fasterxml/jackson/jaxrs/cfg/MapperConfiguratorBase.java:[112,15] cannot find symbol
  symbol:   method setAnnotationIntrospector(com.fasterxml.jackson.databind.AnnotationIntrospector)
  location: variable mapper of type com.fasterxml.jackson.databind.ObjectMapper
[ERROR] /C:/Users/Admin/IdeaProjects/__OFFICIAL/jackson-jaxrs-providers/base/src/main/java/com/fasterxml/jackson/jaxrs/util/EndpointAsBeanProperty.java:[72,23] cannot find symbol
  symbol:   method add(java.lang.annotation.Annotation)
  location: variable am of type com.fasterxml.jackson.databind.introspect.AnnotationMap
```
How to? one or another (Travis builds??)

**Comment by cowtowncoder** [comment]
Exceptions are due to on-going refactoring for 3.0.0-SNAPSHOT. So at this point project is not buildable in `master`. `2.9` branch is, and that is the currently active branch from which releases are made; 3.0 is still quite far from first pre-releases.
I should be able to fix last couple of problems soon, hopefully tonight.

**Comment by soberich** [comment]
It was all good last time.
I builded it and it worked the next day as you said.

**Comment by cowtowncoder** [comment]
@soberich I have tried to fix some remaining issues, which include:

1. Not all projects have all Travis settings for automatic snapshot deploy (it requires keys etc)
2. Some projects have old settings in which URL for snapshot repo is in parent -- but that obviously won't work for clean builds (since parent itself comes from snapshots)

but we should be close to fully functioning snapshot builds, if not completely there. So, if you find specific artifact being problematic, please let us know and we will try to take care of it.
