### ISSUE TITLE
Cannot compile class extending JacksonJaxbJsonProvider

### ISSUE THREAD

**Issue by jvdvegt** [FasterXML/jackson-jaxrs-providers#145]
Using 2.12.3(:jakarta), I cannot get javac (11.0.7) to compile this [JacksonJsonProvider.zip](https://github.com/FasterXML/jackson-jaxrs-providers/files/6435457/JacksonJsonProvider.zip) (generated with SwaggerCodeGen, but that's not related).

I compile like this: 

`javac -classpath .\jakarta.ws.rs-api-3.0.0.jar;.\jackson-dataformat-yaml-2.12.3;.\jackson-jaxrs-base-2.12.3.jar;.\jackson-jaxrs-json-provider-2.12.3-jakarta.jar;.\jackson-module-jaxb-annotations-2.12.3-jakarta.jar;.\jackson-databind-2.12.3.jar JacksonJsonProvider.java`

which results in this short error message:

    JacksonJsonProvider.java:17: error: cannot access MessageBodyReader
    public class JacksonJsonProvider extends JacksonJaxbJsonProvider {
           ^
      class file for javax.ws.rs.ext.MessageBodyReader not found
    1 error

The only reference to **javax**.ws.rs.ext (not jakarta!) I can find is in [JacksonJsonProvider.java](https://github.com/FasterXML/jackson-jaxrs-providers/blob/master/json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProvider.java#L7) and [here](https://github.com/FasterXML/jackson-jaxrs-providers/blob/master/json/src/main/java/com/fasterxml/jackson/jaxrs/json/JacksonJsonProvider.java#L17), but I don't fully understand the javax --> jakarta transition so I'm not sure that's causing the error.

I'm on Windows 10 btw, with AdoptOpenJdk.

**Comment by cowtowncoder** [comment]
Javax->Jakarta is a humongous mess, royal PITA with sprinkles on top. :-(

But... If you don't want Jakarta variant, remove "jakarta" classifier; vanilla version relies on old javax. dependencies. Your JAX-RS container must use same flavor for it to work, too.

For Jackson 2.13 I am thinking of fully forking this package so that there will new coordinates -- classifier approach is problematic due to many things, including difficult in post-processing module-info etc.

**Comment by cowtowncoder** [comment]
Not sure how I can help here, unfortunately; closing.
