### ISSUE TITLE
Rename "com.fasterxml.jackson" -> "tools.jackson"

### ISSUE THREAD

**Issue by cowtowncoder** [FasterXML/jackson-jaxrs-providers#158]
As the main task for JSTEP-1 (https://github.com/FasterXML/jackson-future-ideas/wiki/JSTEP-1) we need to:

1. Change Maven package group id from "com.fasterxml.jackson.core" to "tools.jackson.core"
2. Change Java Package name from "com.fasterxml.jackson.core" to "tools.jackson.core"

(and so on for sub-packages)

as well as all secondary changes for OSGi and Java module system.

**Comment by GedMarc** [comment]
:O :O

Did you get the domain tools.jackson.core? Are you sure you can publish that to maven central without owning the domain?!?!? 

I don't even know if its possible to buy a jackson.tools domain?
I'm not sure if I missed it, was this an internal or a community driven decision?

Prove Domain Ownership
Now that you have an account the next step in the process is to prove ownership of the domain that matches the group that you’d like to publish to. Usually this is your domain name in reverse, so something like com.company if your domain is company.com. Since our developer community is at solace.community this meant we would publish to the community.solace group.

To prove that we own this domain I had to execute a few simple steps:

Open a [New Project Ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134) with OSSRH.
Follow the instructions request in the ticket to addd a DNS TXT record to our domain.
Wait a few hours (it says it could take up to 2 business days) for the DNS TXT record to be verified.
Check the ticket for confirmation that domain ownership has been confirmed.
Make a note to comment on this ticket after your first release to enable syncing to maven central!
✅ Domain ownership proven
