### ISSUE TITLE
Which release is compatible with java17

### ISSUE THREAD

**Issue by QiuSoft** [FasterXML/jackson-jaxrs-providers#180]
Which release is compatible with java17，i haven't find any relation info

**Comment by cowtowncoder** [comment]
@QiuSoft This is not a question that is easy to answer since it is not yes/no answer (as in, all versions work to some degree, some older ones may have issues with some aspects).

But newer the version, better it works, as general guideline.

So go with 2.16.0 if possible. If not, 2.15.x, then 2.14.x and so forth. Use the newest.

Also, for questions like this please use mailing list:

https://groups.google.com/g/jackson-user
