### ISSUE TITLE
MessageBodyReader & Writer in META-INF/service issues...

### ISSUE THREAD

**Issue by pnsantos** [FasterXML/jackson-jaxrs-providers#39]
Hi, I've recently ran into a problem trying to use ackson-jaxrs-json-provider 2.3.0 with Jersey 2.4.1. The problem has to do with the automatic scanning that Jersey does of META-INF/services which can't be disabled otherwise CDI stops functioning.

The problem is that if I want to create a custom ContextResolver (to configure some global Jackson options) that context resolver, and consequently the corresponding object mapper is completly ignored unless I remove the META-INF/services folder.

The issue came up a while ago in Jersey's list ([see this post](https://java.net/projects/jersey/lists/users/archive/2013-12/message/67)). I'm far from an expert but is it absolutely necessary to include these? can (as per the sugestion in the mentioned post) these two files (MessageBodyReader and MessageBodyWriter) be included in a seperate jar?

**Comment by cowtowncoder** [comment]
As per PR just merged, second set of jars with classifier of `no-metainf-services` will be built, deployed.
Will be included in 2.6.0 (not yet included in rc1 that went out few days ago, but will be in rc2 and final).

**Comment by jhaber** [comment]
If possible I would strongly, strongly recommend not using a qualifier but instead modifying the version number, something to the effect of 2.6.0-no-metainf-services. The issue with using a qualifier is that it changes the maven coordinates, meaning that you could get _both_ jackson-jaxrs-json-provider:2.6.0 and jackson-jaxrs-json-provider:2.6.0:no-metainf-services in your dependency tree. By modifying the version instead of using a qualifier, they will still have the same maven coordinates so you can only end up with one in your dependency tree. This allows users to easily pick which one they want to use and not have to worry about adding exclusions all over the place to prevent the undesirable one from sneaking in as well.

**Comment by cowtowncoder** [comment]
@jhaber Do you know of a way to automatically release concurrent versions, similar to how qualifier approach works?
