### ISSUE TITLE
[2.8] Support compact serialization of Link, deserialization

### ISSUE THREAD

**Issue by xenoterracide** [FasterXML/jackson-jaxrs-providers#48]
serialization of a [Link](https://jax-rs-spec.java.net/nonav/2.0/apidocs/javax/ws/rs/core/Link.html) seems too detailed. I realize that I can write a customer serializer, but I think that the default should be simpler like the `uri`, `rel`, `title` and `type`, and imho only if the values aren't null, certainly the attached `uriBuilder` should not have been included in the json output.

```
"link":{"uri":"http://127.0.0.1:8080/NornLM/activities/d1039a2c-e939-4f84-a790-9d8304fe62d2","uriBuilder":{"host":"127.0.0.1","scheme":"http","port":8080,"userInfo":null,"path":"/NornLM/activities/d1039a2c-e939-4f84-a790-9d8304fe62d2","query":null,"fragment":null,"pathParamNamesInDeclarationOrder":[]},"rel":"item","rels":["item"],"title":null,"params":{"rel":"item"},"type":null}
```

migrated from [jackson-core#135](https://github.com/FasterXML/jackson-core/issues/135)

**Comment by cowtowncoder** [comment]
Another thing to note is that `Link` is for JAX-RS 2.0, not 1.1. Not sure if we can yet drop 1.x support?

**Comment by cowtowncoder** [comment]
Ok. Since we are very close to 2.7 release, I will postpone this for Jackson 2.8, to allow for discussion on JAX-RS 2.0. I suspect upgrade is fine, but due to potential compatibility issues do not want to push this quite yet.

I will actually add a skeletal version of datatype module, but will not connect it to be pushed as an artifact.

**Comment by Dichotomia** [comment]
Any news about this functionality?

**Comment by cowtowncoder** [comment]
@Dichotomia I haven't had time to work on this, although I did add `datatypes` within repository.
If anyone has time to help that'd be great; otherwise I will eventually get to this. 2.8 itself is still at least a month out, but getting this done early would help it be included in the first RC,

**Comment by cowtowncoder** [comment]
Datatype module added under `datatypes/`, Maven coordinates:

```xml
  <groupId>com.fasterxml.jackson.datatype</groupId>
  <artifactId>jackson-datatype-jaxrs</artifactId>
```

and module class name `Jaxrs2TypesModule`.

Note that for now no attempt is made to auto-register since I don't trust I can ensure all `ObjectMapper` instances would be configured. But users typically have to choose other datatype modules as well so it should not be big deal.

It would also make sense to see what other JAX-RS 2 datatypes should be supported.

**Comment by Dichotomia** [comment]
Good job!
