### ISSUE TITLE
Add support for JsonViews on inputs to JAX-RS consumers

### ISSUE THREAD

**Issue by molexx** [FasterXML/jackson-jaxrs-providers#57]
A JAX-RS endpoint may be annotated with @JsonView(PublicView.class) so that when the result object is serialised the View is applied so only the specified properties are included.

There is currently no way to specify a View to use when deserialising the inputs. It would be good to be able to do this so a particular endpoint can only accept and set certain properties.

I agree with Tatu below - a parameter annotation of @JsonView would be ideal for consistency and context; if that cannot work then a method annotation @JsonRequestView is good too.

Please document the expected behaviour when no annotation is provided for an input; currently it accepts/populates all properties that have a @JsonView annotation regardless of the View classes they reference.

From Tatu on jackson-user: https://groups.google.com/forum/#!topic/jackson-user/r8Tzt36tpk0

>Technically speaking Jackson can apply JSON View for deserialization too, but you are right this is not connected by Jackson JAX-RS provider.
>The question is how this should be indicated. If JAX-RS passes annotations for actual parameter, we could do:

>@JsonView(ViewForResponse.class)
>public ResponseValue method(@JsonView(ViewForRequest.class) InputValue value) { /.... }

>but I am not 100% sure if this is how things work (it might be that only method-annotations are passed; or perhaps combination of method and parameter ones).

>If this does not work, it'd be necessary to add a new annotation type for Jackson JAX-RS provider (@JsonRequestView?).
>This should be easy enough to do.

**Comment by todd-richmond** [comment]
It would be helpful to be able to be able to specify the request and response views separately because you may want to enable setting fields that are not returned for the same REST resource.

For example, PATCH on a resource might allow setting a password or other field, but the field would not be returned (if PATCH returns the new, complete resource)

Would that require @JsonRequestView or just two params to @JsonView (preferred)?

**Comment by cowtowncoder** [comment]
@todd-richmond Yes absolutely. There is no way to pass two parameters without changing definition of `@JsonView`, but the idea would rather be that separate `@JsonView` was used for method parameter that binds payload; and method annotation would only refer to output view used.

**Comment by cowtowncoder** [comment]
Looking at code, it looks as if `@JsonView` might already work, if applied to arguments. I'll add a unit test to verify that, but to me JAX-RS seems to be passing things so that:

1. Method-annotations are only passed when finding serializer for result value
2. Parameter-annotations are only passed when finding deserializer for specific parameter

If so, things would "just work", and quite as expected. But I will try to test to verify my understanding is correct here.

**Comment by cowtowncoder** [comment]
Ok, yes, things should "just work" as is. Test case is roughly like so:

```java
    @JsonPropertyOrder({ "x", "y" })
    public static class Point {
        @JsonView(ParamView.class)
        public int x;

        @JsonView(ResultView.class)
        public int y;

        protected Point() { }
        public Point(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }

    @Path("/annotated")
    public static class Resource
    {
        @Path("view")
        @POST
        @Consumes(MediaType.APPLICATION_JSON)
        @Produces(MediaType.APPLICATION_JSON)
        @JsonView(ResultView.class)
        public Point withPoint(@JsonView(ParamView.class) Point input) {
            return new Point(input.x + 1, input.y + 1);
        }
    }
```

and verifies that `y` is not included in incoming value; and conversely `x` not included in response (actual test has bit more fluff).

**Comment by cowtowncoder** [comment]
Ok, so: given that with Jackson 2.5 it is both possible to add `@JsonView` on input arguments (which get bound via deserialization) AND since JAX-RS module actually handles this, I think this has already been resolved. Closing as such.
