### ISSUE TITLE
Jackson OSGi metadata is incomplete

### ISSUE THREAD

**Issue by timothyjward** [FasterXML/jackson-jaxrs-providers#93]
My primary issue is the following:

The Jackson JAX-RS JSON provider provides JacksonJaxbJsonProvder (and other types) as exported API. These types rely on the use of Runtime retained JAX-RS annotations to work, without them the JAX-RS provider has no idea what to do with the type. As a result the JAX-RS API must be shared between Jackson and the third party constructing the JAX-RS server/client. If these types are not shared then the whole thing breaks

This is a classic transitive dependency situation that should be fixed by adding a uses constraint on the export of the Jackson package. This would normally be generated automatically by tooling, but the Jackson project seems to manually generate OSGi metadata. Manual generation is hard and error prone - I would suggest fixing this by using a tool like the bnd-maven-plugin (https://github.com/bndtools/bnd/tree/3.3.0.REL/maven/bnd-maven-plugin).

In any event, a correctly formatted uses clause needs to be added to *every* JAX-RS provider which provides the annotations.

**Comment by cowtowncoder** [comment]
PRs highly welcome here; I'm happy to help support OSGi compatibility, but I don't use it myself anywhere so I unfortunately can not really evaluate how well it works. So I rely on others help, and we do have more OSGi-savvy contributors around (like @benson-basis I think).

Now: Jackson does not generate these manually but uses `maven-bundle-plugin` from Felix project.
Basic configuration is defined in parent pom (`oss-parent` via `jackson-parent`), although individual projects do override some of the settings. So it should be just a question of changing such overrides, mostly.
I don't know differences between different plug-ins, although at this point in time I wouldn't be very eager to change the plug-in due to potential for major breakage. But if there are known issues with `maven-bundle-plugin` (3.0.1) that we are using, please let us know.

**Comment by cowtowncoder** [comment]
Thanks again for the fix!
