### ISSUE TITLE
com.fasterxml.jackson.databind.util.BeanUtil.okNameForGetter

### ISSUE THREAD

**Issue by Dakado** [FasterXML/jackson-jaxrs-providers#99]
I am getting this error while using the newest version of jackson core and databind:

`java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForGetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;Z)Ljava/lang/String;`

`java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.util.BeanUtil.okNameForGetter(Lcom/fasterxml/jackson/databind/introspect/AnnotatedMethod;Z)Ljava/lang/String;
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector.findNameForSerialization(JaxbAnnotationIntrospector.java:824)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addGetterMethod(POJOPropertiesCollector.java:519)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods(POJOPropertiesCollector.java:482)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collect(POJOPropertiesCollector.java:234)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.collectProperties(BasicClassIntrospector.java:142)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:68)
	at com.fasterxml.jackson.databind.introspect.BasicClassIntrospector.forSerialization(BasicClassIntrospector.java:11)
	at com.fasterxml.jackson.databind.SerializationConfig.introspect(SerializationConfig.java:530)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:133)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1077)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1037)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:445)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:599)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:93)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2818)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2275)`

**Comment by cowtowncoder** [comment]
This means that version of `jackson-module-jaxb-annotations` you have differs from `jackson-databind` so that they have different minor versions. While some mismatch versions work, in this case difference is too big;  `jackson-module-jaxb-annotations` was compiled with version of databind different from one you are including.

So you need to check which versions are deployed. Note also that "newest" is not necessarily very clear; I assume you mean 2.8.7 (latest stable), but it could also mean `2.9.0.pr1`.
Regardless you have to ensure compatible versions are used.

One thing that may be useful is to use `jackson-bom` dependencty (it's pom, so needs scope "import"), which contains full set of consistent versions of all standard Jackson components.
This should prevent problems like one you describe.

**Comment by Dakado** [comment]
I use the version 2.8.7 of both jaxb-annotations and jackson-databind and still get this error.

**Comment by Dakado** [comment]
Or make it differently if I use this version (which I originally wanted to use but since I got errors I decided to use the latest one but still got errors) https://mvnrepository.com/artifact/com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/2.6.5 what dependiencies should my project use then ? On the link I sent you it says that it needs:

jackson core 2.6.5
jackson databind 2.6.5
jaxrs-base 2.6.5

Which is actually not true, so what versions do I really need to make jackson-json-provider 2.6.5 work ?


Thanks.

**Comment by cowtowncoder** [comment]
@Dakado Yes you must use same minor version FOR ALL JACKSON COMPONENTS. This is true.

You have some sort of version discrepancy on your side, and I can not help with that, certainly not if your only claim is "no that doesn't work".

The only other thing I will mention before letting you figure out your problem is that method `BeanUtil.okNameForGetter()` was added in Jackson 2.5, as per Javadocs in sources.
So it seems like that you have earlier version (perhaps 2.4) of `jackson-databind`, which does not have that method. It's up to you to find where and how that would come. Not me to somehow prove you do not have the problem.

**Comment by Dakado** [comment]
I use the version 2.6.5 for all jackson components. Basically I am implementing this API: https://github.com/gopaycommunity/gopay-java-api and it requieres this module: https://mvnrepository.com/artifact/com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/2.6.5


I downloaded all depediencies via maven and I got abovementioned error so it must be something wrong with jackson 2.6.5 or there are bad dependiencies listed for jackson-jaxrs-json-provider 2.6.5

**Comment by cowtowncoder** [comment]
@Dakado You may be new to open source communities, so I will try to be more patient with you than I typically am with users that appear to be wasting of my time.

The way things work is that for maintainers like me to be able to help you, they must be able to reproduce your problem. For all I know, there is something wrong with your setup, connectivity or anything -- I have no way of seeing what you see. And when I can not see what is actually happening, I can not help. Since literally thousands of developers are successfully using Jackson version 2.6 -- exact version `2.6.5` was downloaded 107,243 times from Maven Central last month! -- it is somewhat annoying that you claim to know for sure there is something wrong with 2.6.5. Instead of problem being due to something in your project setup.

What helps is a reproduction: a project you create that I can install and that exhibits the problem you have. That way I can see that there is a failure, and hopefully help diagnose it. This does not exist.
And until such reproduction exists I can not help you further with your problem.

**Comment by trajano** [comment]
As for me I used

```
      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>2.9.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

And 

```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
```
I did find it odd that `jackson-annotations` is on 2.9.0 and databind and core are both on 2.9.1.

**Comment by trajano** [comment]
What had worked for me was downgrading to

      <dependency>
        <groupId>com.fasterxml.jackson</groupId>
        <artifactId>jackson-bom</artifactId>
        <version>2.8.10</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

So it may be a bug in the 2.9.1 BOM.

**Comment by cowtowncoder** [comment]
@trajano `jackson-annotation` version of 2.9.0 is correct. While other patch versions are produced for users who prefer exactly same version, there are absolutely no changes since .0 for any annotations package. Patch version will be dropped from annotations package of Jackson 3, to reduce confusion.
However I am not sure how this would be related to the issue at hand here.

**Comment by trajano** [comment]
When I use the current version I get the same error as @dAkado I found that the old version worked correctly. Hopefully this may help people experiencing the same problem.  At least as a quick workaround.
